apiVersion: v2
appVersion: 18.6.8
dependencies:
- name: teleport-kube-updater
  repository: ""
  version: 18.6.8
description: Teleport provides a secure SSH, Kubernetes, database and application
  remote access solution that doesn't get in the way.
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
- Teleport
name: teleport-kube-agent
version: 18.6.8
