apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeaid-agent.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeaid-agent.labels" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    {{- toYaml .Values.appConfig | nindent 4 }}
