apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeaid-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeaid-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "kubeaid-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeaid-agent.selectorLabels" . | nindent 8 }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ tpl (toYaml .Values.appConfig) . | sha256sum }}
        {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "kubeaid-agent.name" . }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          env:
            {{- with .Values.deployment.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.appConfig.argocd.authTokenSecretRef }}
            {{- if and .secretName .key }}
            - name: KUBEAID_AGENT_ARGOCD_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}

            {{- with .Values.appConfig.kubeaidConfig.repo.auth.basic.usernameSecretRef }}
            {{- if and .secretName .key }}
            - name: KUBEAID_AGENT_REPO_AUTH_BASIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}

            {{- with .Values.appConfig.kubeaidConfig.repo.auth.basic.passwordSecretRef }}
            {{- if and .secretName .key }}
            - name: KUBEAID_AGENT_REPO_AUTH_BASIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}

            {{- with .Values.appConfig.kubeaidConfig.repo.auth.sshKey.passwordSecretRef }}
            {{- if and .secretName .key }}
            - name: KUBEAID_AGENT_REPO_AUTH_SSHKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
          args:
            - "--config-file-path=/etc/kubeaid-agent/config.yaml"
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.server.port }}
              protocol: TCP
          {{- with .Values.deployment.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: config.yaml
              mountPath: /etc/kubeaid-agent/config.yaml
              readOnly: true
            - name: kubeaid-git-credentials
              subPath: id_rsa
              mountPath: {{ .Values.appConfig.kubeaidConfig.repo.auth.sshKey.sshPrivateKey }}
              readOnly: true
            - name: kubeaid-git-credentials
              subPath: known_hosts
              mountPath: {{ .Values.appConfig.kubeaidConfig.repo.auth.sshKey.hostKeyFile }}
              readOnly: true
            - name: obmondo-api-tls
              subPath: tls.key
              mountPath: {{ .Values.appConfig.obmondoAPI.tls.keyFile }}
              readOnly: true
            - name: obmondo-api-tls
              subPath: tls.crt
              mountPath: {{ .Values.appConfig.obmondoAPI.tls.certFile }}
              readOnly: true
            - name: obmondo-api-tls
              subPath: ca.crt
              mountPath: {{ .Values.appConfig.obmondoAPI.tls.caCertFile }}
              readOnly: true
            - name: tmp
              mountPath: /tmp
          {{- with .Values.deployment.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kubeaid-agent.fullname" . }}-config
        - name: obmondo-api-tls
          secret:
            secretName: {{ .Values.obmondoAPITLSSecretName }}
        - name: kubeaid-git-credentials
          secret:
            secretName: kubeaid-git-credentials
        - name: tmp
          emptyDir: {}
        {{- with .Values.deployment.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
