{{- if not .Values.externalSecret.enabled }}  
apiVersion: v1  
kind: Secret  
metadata:  
  name: {{ include "openobserve-collector.fullname" . }}  
type: Opaque  
stringData:  
  OPENOBSERVE_AUTH_TOKEN: "{{ .Values.auth.OPENOBSERVE_AUTH_TOKEN }}"  
  OPENOBSERVE__K8S_EVENTS_AUTH_TOKEN: "{{ .Values.auth.OPENOBSERVE__K8S_EVENTS_AUTH_TOKEN }}"  
{{- end }}