apiVersion: v2
appVersion: 2.8.0
description: The OpenSearch Operator Helm chart for Kubernetes
home: https://opensearch.org
name: opensearch-operator
sources:
- https://github.com/opensearch-project/OpenSearch
- https://github.com/opensearch-project/opensearch-k8s-operator
type: application
version: 2.8.1
