annotations:
  artifacthub.io/changes: |
    - Add support for mariadb
  artifacthub.io/images: |
    - name: friendica
      image: friendica:2021.04
apiVersion: v2
appVersion: "2021.04"
dependencies:
- name: common
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.9
- condition: mariadb.enabled
  name: mariadb
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~1.0.3
description: Welcome to the free social web.
home: https://github.com/nicholaswilde/helm-charts/tree/main/charts/friendica
icon: https://d1q6f0aelx0por.cloudfront.net/product-logos/library-friendica-logo.png
keywords:
- friend
- social
maintainers:
- email: ncwilde43@gmail.com
  name: nicholaswilde
name: friendica
sources:
- https://friendi.ca/
- https://hub.docker.com/_/friendica
type: application
version: 1.0.0
