apiVersion: v2
appVersion: v5.0.19
description: Deploy Calcom in a Helm Chart
home: https://pyrrha.github.io/calcom-helm/
keywords:
- kubernetes
- chart
- schedule
- conference
- calendar
- visio
- helm
- meeting
- cal
- appointment
- calcom
maintainers:
- name: Pyrrha
  url: https://github.com/Pyrrha/calcom-helm
name: calcom
sources:
- https://github.com/Pyrrha/calcom-helm
type: application
version: 0.8.6
