apiVersion: v2
appVersion: 19.0.0-dev
description: 'Library chart containing all the templates to deploy a Teleport updater.
  IMPORTANT: this chart is not meant for public consumption, stability and versioning
  guarantees do not apply here. '
icon: https://goteleport.com/static/teleport-symbol-bimi.svg
keywords:
- Teleport
- updater
- library
name: teleport-kube-updater
type: library
version: 19.0.0-dev
