apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-config
  namespace: seaweedfs
type: Opaque
stringData:
  seaweedfs_s3_config: |
    {
        "identities": [
            {
                "name": "<user-name>",
                "credentials": [
                    {
                        "accessKey": "",
                        "secretKey": ""
                    }
                ],
                "actions": [
                    "Read:<bucket-name>",
                    "Write:<bucket-name>",
                    "List:<bucket-name>",
                    "Tagging:<bucket-name>",
                    "Admin:<bucket-name>"
                ]
            },
        ]
    }
