apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "puppetserver.name" . }}-g10k-code-config
data:
  g10k_code.yaml: |
    # The location to use for storing cached Git repos
    cachedir: '/etc/puppetlabs/code/g10k_cache'
    sources:
      :linuxaid:
        remote: '{{ .Values.puppetserver.puppetserver.puppeturl }}'
        basedir: '{{ .Values.puppetserver.puppetserver.puppetbasedir }}'
