openobserve:
  etcd:
    image:
      registry: docker.io
      repository: bitnamilegacy/etcd
      tag: 3.5.8-debian-11-r4
      pullPolicy: IfNotPresent
      digest: ""
    volumePermissions:
      image:
        registry: docker.io
        repository: bitnamilegacy/os-shell
        tag: 12-debian-12-r30
        pullPolicy: IfNotPresent
        digest: ""
