{{- if and .Values.enterprise.enabled .Values.enterprise.dex.enabled (not .Values.externalSecret.enabled) }}  
apiVersion: v1  
kind: Secret  
metadata:  
  name: {{ include "openobserve.fullname" . }}-dex  
  namespace: {{ .Release.Namespace | quote }}  
  labels:  
    {{- include "openobserve.labels" . | nindent 4 }}  
type: Opaque
stringData:  
  dexConfig: |  {{ .Values.enterprise.dex.config | toYaml | nindent 4 }}
{{- end }}
