{{- if and .Values.postgres.enabled (not .Values.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openobserve.fullname" . }}-openobservepguser
  namespace: {{ .Release.Namespace | quote }}
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.postgres.spec.username | b64enc}}  # openobserve # this should match the role name in cluster
  password: {{ .Values.postgres.spec.password | b64enc}}  # Batman123
{{- end }}
