apiVersion: v2
appVersion: v0.12.4-nginx
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.7.10
- condition: valkey.enabled
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.4.7
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.5.7
description: A Helm chart for deploying Pixelfed on Kubernetes
maintainers:
- email: jessebot@linux.com
  name: jessebot
  url: https://github.com/jessebot
name: pixelfed
type: application
version: 0.23.0
