apiVersion: v2
appVersion: 1.12.10
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.2.0
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.5.0
description: Helm chart for Castopod - free and open-source hosting platform for podcasters.
home: https://castopod.org/
icon: https://raw.githubusercontent.com/hiimluck3r/helm-charts/master/etc/icons/castopod-logo.jpg
keywords:
- castopod
- storage
- http
- web
- php
maintainers:
- email: luck3rinc@yandex.ru
  name: hiimluck3r
  url: https://github.com/hiimluck3r
name: castopod
sources:
- https://github.com/hiimluck3r/helm-charts/castopod
type: application
version: 1.12.10
