apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.global.clusterName }}
  annotations:
    # Use fixed node names for bare metal servers, since there are storage integrations that allow
    # you to use the storage of the bare metal servers and that work with fixed node names.
    capi.syself.com/constant-bare-metal-hostname: "true"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - {{ .Values.global.pods.cidrBlock | default "10.244.0.0/16" }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: {{ .Values.global.clusterName }}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: {{ .Values.global.clusterName }}-control-plane 
